### ISSUE TITLE
Bar visualization - new features

### ISSUE THREAD

**Issue by coreation** [tdt/formatters#6]
Currently the bar formatter only allows for basic usage. Just like the Map visualization it's been implemented as a starting point to build upon.

Ideas:

Add x & y-axis, and allow to pass along the names in the query string (e.g. x_axis="trees")
Allow for more than one value to be shown, this might however imply that for example if a data.x and a data.y which have a large range gap  ( data.x =[1-10] and data.y = [ 10000-10000000] ) the chart will become a little less irrelevant. Which may point out that perhaps we should opt to allow multiple bar-charts displays next to eachother?

**Comment by dive-michiel** [comment]
I'll add some visual information to improve the currently almost empty chart ;)

**Comment by dive-michiel** [comment]
Removed BAR fomatter, added GRAPH formatter, options:

• values: comma seperated list of the properties to plot
• type: bars | lines (default: lines)

**Comment by coreation** [comment]
Looks amazing, job well done!
