### ISSUE TITLE
JSON unescape slashes

### ISSUE THREAD

**Issue by pietercolpaert** [tdt/formatters#8]
Apparently this constant is unknown on some servers:

https://github.com/tdt/formatters/blob/development/src/tdt/formatters/strategies/JSON.php#L28

[error] [...] PHP Notice:  Use of undefined constant JSON_UNESCAPED_SLASHES - assumed 'JSON_UNESCAPED_SLASHES' in tdt/formatters/src/tdt/formatters/strategies/JSON.php on line 28

~# php --version
PHP 5.3.3-7+squeeze14 with Suhosin-Patch (cli) (built: Aug  6 2012 20:08:59) 

And the docs:

http://php.net/manual/en/function.json-encode.php

Were added in 5.4.0:
    JSON_PRETTY_PRINT, JSON_UNESCAPED_SLASHES, and JSON_UNESCAPED_UNICODE options were added.

Since we support >=5.3, we'd better find an alternative for this.

**Comment by coreation** [comment]
We could first look at what the ETA on this is, and then decide whether to address this. If this is fixed within a week or two, then we could revert the development branch, and make a separate branch for the escaping slashes. If however the solution we provide is simple and fast to deploy, then we should go for it.

**Comment by pietercolpaert** [comment]
Went for it. Fixed. Not that big of a deal, right?

**Comment by pietercolpaert** [comment]
Also sent a pull request towards ARC2: https://github.com/pietercolpaert/arc2/commit/7e12930cee324d58530570d51beaabbf5468a9e1

**Comment by coreation** [comment]
:+1:
